Traceback (most recent call last):
  File "dcgan_mnist.py", line 13, in <module>
    from keras.models import Sequential
ImportError: No module named keras.models
